"""Unit tests for the PROV-O provenance record builder."""

import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from marimba.core.utils import provenance
from marimba.core.utils.provenance import MARIMBA_REPOSITORY_URL, build_provenance_document, normalise_repository_url

_STARTED = datetime(2026, 6, 22, 14, 25, 0, tzinfo=UTC)
_PACKAGED = datetime(2026, 6, 22, 14, 30, 0, tzinfo=UTC)
_DATASET_IRI = "urn:uuid:u"
_COMMIT = "a9278ac6479587bd4d7f90ad56f58795cafd108e"


def _build(**overrides: object) -> dict[str, Any]:
    """Build a provenance document with sensible defaults, overridable per test."""
    kwargs: dict[str, Any] = {
        "image_set_uuid": "u",
        "dataset_name": "DS",
        "dataset_version": "1.0",
        "pipeline_repos": {},
        "packaged_datetime": _PACKAGED,
        "marimba_version": "1.1.0",
        "started_datetime": _STARTED,
    }
    kwargs.update(overrides)
    return build_provenance_document(**kwargs)  # type: ignore[arg-type]


def _node(document: dict[str, Any], node_id: str) -> dict[str, Any]:
    """Return the @graph node with the given @id."""
    return next(n for n in document["@graph"] if n.get("@id") == node_id)


def _init_repo(repo: Path, *, tag: str | None = None, origin: str | None = None) -> None:
    """Create a git repo with one commit, optionally tagged and with an origin remote."""
    repo.mkdir()

    def _git(*args: str) -> None:
        subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)  # noqa: S607

    _git("init", "-b", "main")
    _git("config", "user.email", "t@example.com")
    _git("config", "user.name", "Test")
    (repo / "pipeline.py").write_text("x = 1\n")
    _git("add", ".")
    _git("commit", "-m", "initial")
    if tag:
        _git("tag", tag)
    if origin:
        _git("remote", "add", "origin", origin)


class TestNormaliseRepositoryUrl:
    """Git remotes are normalised to browsable https URLs."""

    @pytest.mark.unit
    @pytest.mark.parametrize(
        ("remote", "expected"),
        [
            (
                "https://github.com/csiro-fair/mritc-demo-pipeline.git",
                "https://github.com/csiro-fair/mritc-demo-pipeline",
            ),
            ("https://github.com/csiro-fair/mritc-demo-pipeline/", "https://github.com/csiro-fair/mritc-demo-pipeline"),
            ("git@github.com:csiro-fair/mritc-demo-pipeline.git", "https://github.com/csiro-fair/mritc-demo-pipeline"),
            (
                "ssh://git@codebase.helmholtz.cloud:2222/datahub/pipe.git",
                "https://codebase.helmholtz.cloud/datahub/pipe",
            ),
            ("https://user:token@gitlab.com/org/repo.git", "https://gitlab.com/org/repo"),
            ("http://git.example.org/org/repo.git", "http://git.example.org/org/repo"),
            ("git://github.com/org/repo.git", "https://github.com/org/repo"),
        ],
    )
    def test_remote_urls_are_normalised(self, remote: str, expected: str) -> None:
        """Scheme variants and scp-style remotes collapse to one https form without credentials or .git."""
        assert normalise_repository_url(remote) == expected

    @pytest.mark.unit
    @pytest.mark.parametrize(
        "remote",
        ["/home/user/.cache/marimba-e2e/pipeline", "C:\\repos\\pipeline", "file:///srv/git/pipeline.git", "https://"],
    )
    def test_non_remote_urls_are_rejected(self, remote: str) -> None:
        """Local paths and file URLs are never recorded as a code repository."""
        assert normalise_repository_url(remote) is None


class TestBuildProvenanceDocument:
    """Test the structure and content of the provenance document."""

    @pytest.mark.unit
    def test_context_uses_only_standard_vocabularies(self) -> None:
        """The JSON-LD context declares PROV-O, schema.org and XSD and no Marimba-specific terms."""
        doc = _build()
        assert set(doc["@context"]) == {"prov", "schema", "xsd"}
        assert isinstance(doc["@graph"], list)
        for node in doc["@graph"]:
            assert not any(key.startswith("marimba:") for key in node), node

    @pytest.mark.unit
    def test_node_ids_are_absolute_under_the_dataset_urn(self) -> None:
        """Every node is an absolute IRI rooted at the dataset's urn:uuid, so the graph is location-independent."""
        doc = _build(image_set_uuid="110cae5b")
        ids = [n["@id"] for n in doc["@graph"]]
        assert ids[0] == "urn:uuid:110cae5b"
        assert all(i.startswith("urn:uuid:110cae5b#") for i in ids[1:])

    @pytest.mark.unit
    def test_dataset_entity_links_to_activity_and_marimba(self) -> None:
        """The dataset entity is a typed Dataset generated by the packaging activity and attributed to Marimba."""
        doc = _build(image_set_uuid="110cae5b", dataset_version="2.0")
        entity = _node(doc, "urn:uuid:110cae5b")
        assert entity["@type"] == ["prov:Entity", "schema:Dataset"]
        assert entity["schema:name"] == "DS"
        assert entity["schema:version"] == "2.0"
        assert entity["prov:generatedAtTime"] == {"@type": "xsd:dateTime", "@value": "2026-06-22T14:30:00Z"}
        assert entity["prov:wasGeneratedBy"] == {"@id": "urn:uuid:110cae5b#packaging"}
        assert entity["prov:wasAttributedTo"] == {"@id": "urn:uuid:110cae5b#marimba"}

    @pytest.mark.unit
    def test_dataset_version_omitted_when_absent(self) -> None:
        """No schema:version is written when the dataset has no version."""
        doc = _build(dataset_version=None)
        assert "schema:version" not in _node(doc, _DATASET_IRI)

    @pytest.mark.unit
    def test_activity_timestamps(self) -> None:
        """The activity carries UTC start and end times and is associated with Marimba."""
        activity = _node(_build(), f"{_DATASET_IRI}#packaging")
        assert activity["@type"] == "prov:Activity"
        assert activity["prov:startedAtTime"]["@value"] == "2026-06-22T14:25:00Z"
        assert activity["prov:endedAtTime"]["@value"] == "2026-06-22T14:30:00Z"
        assert {"@id": f"{_DATASET_IRI}#marimba"} in activity["prov:wasAssociatedWith"]

    @pytest.mark.unit
    def test_activity_start_omitted_when_unknown(self) -> None:
        """No prov:startedAtTime is written when the start time is not supplied."""
        activity = _node(_build(started_datetime=None), f"{_DATASET_IRI}#packaging")
        assert "prov:startedAtTime" not in activity
        assert "prov:endedAtTime" in activity

    @pytest.mark.unit
    def test_marimba_agent_from_release_install(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """A pip-installed release records its PyPI page and release tag but no commit."""
        monkeypatch.setattr(provenance, "_marimba_git_info", dict)
        agent = _node(_build(marimba_version="1.2.0"), f"{_DATASET_IRI}#marimba")
        assert agent["@type"] == ["prov:SoftwareAgent", "schema:SoftwareApplication"]
        assert agent["schema:softwareVersion"] == "1.2.0"
        assert agent["schema:codeRepository"] == MARIMBA_REPOSITORY_URL
        assert agent["schema:installUrl"] == "https://pypi.org/project/marimba/1.2.0/"
        assert agent["schema:url"] == f"{MARIMBA_REPOSITORY_URL}/releases/tag/v1.2.0"
        assert "schema:identifier" not in agent

    @pytest.mark.unit
    def test_marimba_agent_from_source_checkout(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """A source checkout records the commit as a SWHID and permalink; the git tag never overrides the version."""
        monkeypatch.setattr(
            provenance,
            "_marimba_git_info",
            lambda: {"commit": _COMMIT, "tag": "v1.2.0", "dirty": True, "url": "https://example.org/fork"},
        )
        agent = _node(_build(marimba_version="1.2.0"), f"{_DATASET_IRI}#marimba")
        assert agent["schema:softwareVersion"] == "1.2.0"
        assert agent["schema:codeRepository"] == MARIMBA_REPOSITORY_URL
        assert agent["schema:identifier"] == f"swh:1:rev:{_COMMIT}"
        assert agent["schema:url"] == f"{MARIMBA_REPOSITORY_URL}/commit/{_COMMIT}"
        assert "uncommitted changes" in agent["schema:description"]

    @pytest.mark.unit
    def test_marimba_dev_version_has_no_release_links(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """A non-release version string yields neither a PyPI page nor a release-tag URL."""
        monkeypatch.setattr(provenance, "_marimba_git_info", dict)
        agent = _node(_build(marimba_version="1.2.1.dev3"), f"{_DATASET_IRI}#marimba")
        assert "schema:installUrl" not in agent
        assert "schema:url" not in agent

    @pytest.mark.integration
    def test_pipeline_git_provenance_captured(self, tmp_path: Path) -> None:
        """A pipeline backed by a git repo contributes its repository, commit permalink, SWHID and release tag."""
        repo = tmp_path / "repo"
        _init_repo(repo, tag="v1.2.3", origin="git@github.com:csiro-fair/mritc-demo-pipeline.git")

        doc = _build(pipeline_repos={"MRITC": repo})
        agent = _node(doc, f"{_DATASET_IRI}#pipeline-MRITC")
        assert agent["@type"] == ["prov:SoftwareAgent", "schema:SoftwareSourceCode"]
        assert agent["schema:name"] == "MRITC"
        assert agent["schema:codeRepository"] == "https://github.com/csiro-fair/mritc-demo-pipeline"
        commit = agent["schema:identifier"].removeprefix("swh:1:rev:")
        assert len(commit) == 40
        assert agent["schema:url"] == f"https://github.com/csiro-fair/mritc-demo-pipeline/commit/{commit}"
        assert agent["schema:softwareVersion"] == "v1.2.3"
        assert "schema:description" not in agent
        assert {"@id": agent["@id"]} in _node(doc, f"{_DATASET_IRI}#packaging")["prov:wasAssociatedWith"]

    @pytest.mark.integration
    def test_bitbucket_commit_permalink(self, tmp_path: Path) -> None:
        """Bitbucket permalinks use /commits/ rather than /commit/."""
        repo = tmp_path / "repo"
        _init_repo(repo, origin="https://bitbucket.org/org/pipe.git")
        agent = _node(_build(pipeline_repos={"P": repo}), f"{_DATASET_IRI}#pipeline-P")
        assert agent["schema:url"].startswith("https://bitbucket.org/org/pipe/commits/")

    @pytest.mark.integration
    def test_untagged_pipeline_omits_version(self, tmp_path: Path) -> None:
        """A commit that is not on a tag yields no schema:softwareVersion."""
        repo = tmp_path / "repo"
        _init_repo(repo)
        agent = _node(_build(pipeline_repos={"MRITC": repo}), f"{_DATASET_IRI}#pipeline-MRITC")
        assert "schema:softwareVersion" not in agent

    @pytest.mark.integration
    def test_pipeline_without_remote_has_swhid_but_no_urls(self, tmp_path: Path) -> None:
        """A local-only repo still identifies its commit intrinsically, but records no repository or permalink."""
        repo = tmp_path / "repo"
        _init_repo(repo)
        agent = _node(_build(pipeline_repos={"P": repo}), f"{_DATASET_IRI}#pipeline-P")
        assert agent["schema:identifier"].startswith("swh:1:rev:")
        assert "schema:codeRepository" not in agent
        assert "schema:url" not in agent

    @pytest.mark.integration
    def test_dirty_pipeline_tree_is_flagged(self, tmp_path: Path) -> None:
        """Uncommitted changes to tracked files are described so the commit is not taken as the exact code."""
        repo = tmp_path / "repo"
        _init_repo(repo)
        (repo / "pipeline.py").write_text("x = 2\n")
        agent = _node(_build(pipeline_repos={"P": repo}), f"{_DATASET_IRI}#pipeline-P")
        assert agent["schema:identifier"].startswith("swh:1:rev:")
        assert "uncommitted changes" in agent["schema:description"]

    @pytest.mark.unit
    def test_non_git_pipeline_omits_git_fields(self, tmp_path: Path) -> None:
        """A pipeline whose source is not a git repo still appears, without git fields."""
        plain = tmp_path / "plain"
        plain.mkdir()
        agent = _node(_build(pipeline_repos={"P": plain}), f"{_DATASET_IRI}#pipeline-P")
        assert agent["schema:name"] == "P"
        assert "schema:identifier" not in agent
        assert "schema:codeRepository" not in agent
