"""Unit tests for the PROV-O provenance record builder."""

import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from marimba.core.utils.provenance import MARIMBA_REPOSITORY_URL, build_provenance_document

_PACKAGED = datetime(2026, 6, 22, 14, 30, 0, tzinfo=UTC)


def _build(**overrides: object) -> dict[str, Any]:
    """Build a provenance document with sensible defaults, overridable per test."""
    kwargs: dict[str, Any] = {
        "image_set_uuid": "u",
        "dataset_name": "DS",
        "dataset_version": "1.0",
        "pipeline_repos": {},
        "packaged_datetime": _PACKAGED,
        "marimba_version": "1.1.0",
    }
    kwargs.update(overrides)
    return build_provenance_document(**kwargs)  # type: ignore[arg-type]


def _node(document: dict[str, Any], node_id: str) -> dict[str, Any]:
    """Return the @graph node with the given @id."""
    return next(n for n in document["@graph"] if n.get("@id") == node_id)


class TestBuildProvenanceDocument:
    """Test the structure and content of the provenance document."""

    @pytest.mark.unit
    def test_has_jsonld_context_and_graph(self) -> None:
        """The document is JSON-LD with a @context and a @graph."""
        doc = _build()
        assert "prov" in doc["@context"]
        assert isinstance(doc["@graph"], list)

    @pytest.mark.unit
    def test_dataset_entity_links_to_activity_and_marimba(self) -> None:
        """The dataset entity is generated by the packaging activity and attributed to Marimba."""
        doc = _build(image_set_uuid="110cae5b", dataset_version="2.0")
        entity = _node(doc, "urn:uuid:110cae5b")
        assert entity["@type"] == "prov:Entity"
        assert entity["schema:name"] == "DS"
        assert entity["schema:version"] == "2.0"
        assert entity["prov:wasGeneratedBy"] == {"@id": "#packaging"}
        assert entity["prov:wasAttributedTo"] == {"@id": "#marimba"}

    @pytest.mark.unit
    def test_dataset_version_omitted_when_absent(self) -> None:
        """No schema:version is written when the dataset has no version."""
        doc = _build(dataset_version=None)
        assert "schema:version" not in _node(doc, "urn:uuid:u")

    @pytest.mark.unit
    def test_marimba_agent_and_activity_timestamp(self) -> None:
        """The Marimba agent carries its version + repo, and the activity carries the UTC end time."""
        doc = _build()
        marimba_agent = _node(doc, "#marimba")
        assert marimba_agent["@type"] == "prov:SoftwareAgent"
        assert marimba_agent["schema:softwareVersion"] == "1.1.0"
        assert marimba_agent["schema:codeRepository"] == MARIMBA_REPOSITORY_URL

        activity = _node(doc, "#packaging")
        assert activity["@type"] == "prov:Activity"
        assert activity["prov:endedAtTime"]["@value"] == "2026-06-22T14:30:00Z"
        assert {"@id": "#marimba"} in activity["prov:wasAssociatedWith"]

    @pytest.mark.integration
    def test_pipeline_git_provenance_captured(self, tmp_path: Path) -> None:
        """A pipeline backed by a git repo contributes its commit, branch, and release tag."""
        repo = tmp_path / "repo"
        repo.mkdir()

        def _git(*args: str) -> None:
            subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)  # noqa: S607

        _git("init", "-b", "main")
        _git("config", "user.email", "t@example.com")
        _git("config", "user.name", "Test")
        (repo / "pipeline.py").write_text("x = 1\n")
        _git("add", ".")
        _git("commit", "-m", "initial")
        _git("tag", "v1.2.3")

        doc = _build(pipeline_repos={"MRITC": repo})
        agent = _node(doc, "#pipeline-MRITC")
        assert agent["@type"] == "prov:SoftwareAgent"
        assert agent["schema:name"] == "MRITC"
        assert len(agent["marimba:commit"]) == 40
        assert agent["marimba:branch"] == "main"
        assert agent["marimba:tag"] == "v1.2.3"
        assert {"@id": "#pipeline-MRITC"} in _node(doc, "#packaging")["prov:wasAssociatedWith"]

    @pytest.mark.integration
    def test_untagged_pipeline_omits_tag(self, tmp_path: Path) -> None:
        """A commit that is not on a tag yields no marimba:tag."""
        repo = tmp_path / "repo"
        repo.mkdir()

        def _git(*args: str) -> None:
            subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)  # noqa: S607

        _git("init", "-b", "main")
        _git("config", "user.email", "t@example.com")
        _git("config", "user.name", "Test")
        (repo / "pipeline.py").write_text("x = 1\n")
        _git("add", ".")
        _git("commit", "-m", "initial")

        agent = _node(_build(pipeline_repos={"MRITC": repo}), "#pipeline-MRITC")
        assert "marimba:tag" not in agent

    @pytest.mark.unit
    def test_non_git_pipeline_omits_commit(self, tmp_path: Path) -> None:
        """A pipeline whose source is not a git repo still appears, without git fields."""
        plain = tmp_path / "plain"
        plain.mkdir()
        agent = _node(_build(pipeline_repos={"P": plain}), "#pipeline-P")
        assert agent["schema:name"] == "P"
        assert "marimba:commit" not in agent
        assert "schema:codeRepository" not in agent
